spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
logging:
  path: /tmp/spring_logs/
  file: test.log
  level:
    root: DEBUG